const { chromium, expect } = require('playwright/test');
const fs = require('node:fs/promises');
const path = require('node:path');

async function main() {
  if (!process.env.WORKSHOP_SMOKE_URL || !process.env.WORKSHOP_SMOKE_COVER) throw Error('Use workshop_browser_smoke.py');
  const evidence = path.resolve(__dirname, '../data/logs/diagnostics/workshop-browser');
  await fs.mkdir(evidence, {recursive:true});
  const browser = await chromium.launch({channel:'msedge', headless:true});
  const page = await browser.newPage({viewport:{width:1440,height:1000}});
  const errors = [];
  page.on('pageerror', e=>errors.push(e.message));
  try {
    await page.goto(process.env.WORKSHOP_SMOKE_URL);
    await page.locator('#sidebar > button').click();
    const cards = page.locator('#workshop-grid .workshop-tile');
    await expect(cards).toHaveCount(9,{timeout:20000});
    await expect(page.getByRole('textbox',{name:'工坊状态',exact:true})).toHaveValue(/已连接/);
    await page.waitForFunction(()=>Array.from(document.querySelectorAll('#workshop-grid img')).every(i=>i.complete && i.naturalWidth>0));
    await fs.writeFile(path.join(evidence,'gallery-dom.txt'),await page.locator('#workshop-grid').evaluate(e=>e.outerHTML));
    await page.screenshot({path:path.join(evidence,'desktop-grid.png'),fullPage:true});
    const top = await page.locator('.workshop-status-bar').evaluate(e=>Array.from(e.children).map(c=>({y:c.getBoundingClientRect().y,h:c.getBoundingClientRect().height})));
    if (Math.max(...top.map(v=>v.y+v.h))-Math.min(...top.map(v=>v.y+v.h))>3) throw Error('Top controls do not share a row');
    await cards.first().hover();
    await expect(cards.first().locator('.workshop-card-overlay')).toHaveCSS('opacity','1');
    await expect(cards.first()).toContainText('未安装');
    await page.screenshot({path:path.join(evidence,'desktop-hover.png'),fullPage:true});
    await cards.first().getByRole('button',{name:'查看详情',exact:true}).click();
    const modal = page.getByRole('dialog');
    const detail = page.locator('#workshop-dialog-details');
    const close = page.getByRole('button',{name:'关闭',exact:true});
    const actionStatus = page.getByRole('textbox',{name:'操作说明',exact:true});
    await expect(modal).toBeVisible();
    await expect(detail).toContainText('未安装');
    for (const name of ['音色', '作者简介', '许可', '上传时间', '本地安装状态']) await expect(detail).toContainText(name);
    await expect(page.locator('#workshop-inspector')).toHaveCount(0);
    await expect(modal.getByRole('button',{name:'确认安装',exact:true})).toHaveCount(0);
    const compactBox=await modal.boundingBox();
    if (compactBox.height>650) throw Error('Details dialog contains excess empty space');
    await page.screenshot({path:path.join(evidence,'details-modal.png')});
    await page.keyboard.press('Escape');
    await expect(modal).toBeHidden();
    await expect(cards.first().getByRole('button',{name:'查看详情',exact:true})).toBeFocused();
    await cards.first().hover();
    await cards.first().getByRole('button',{name:'安装模型',exact:true}).click();
    await page.getByRole('button',{name:'确认安装',exact:true}).click();
    await expect(actionStatus).toHaveValue(/INSTALL_CONFIRM_REQUIRED/);
    await modal.getByRole('checkbox').check();
    await page.getByRole('button',{name:'确认安装',exact:true}).click();
    await expect(actionStatus).toHaveValue(/安装成功/,{timeout:20000});
    await close.click();
    await expect(modal).toBeHidden();
    await expect(cards.first()).toContainText('已安装');
    await expect(cards.first().getByRole('button',{name:'安装模型',exact:true})).toHaveCount(0);
    await cards.first().hover();
    await cards.first().getByRole('button',{name:'卸载模型',exact:true}).click();
    await page.getByRole('button',{name:'确认卸载',exact:true}).click();
    await expect(actionStatus).toHaveValue(/已卸载/);
    await close.click();
    await expect(modal).toBeHidden();
    await expect(cards.first()).toContainText('未安装');
    await cards.first().hover();
    await cards.first().getByRole('button',{name:'安装模型',exact:true}).click();
    await page.getByRole('button',{name:'恢复安装',exact:true}).click();
    await expect(actionStatus).toHaveValue(/恢复安装/);
    await close.click();
    await expect(modal).toBeHidden();
    await expect(cards.first()).toContainText('已安装');
    await cards.first().hover();
    await cards.first().getByRole('button',{name:'查看详情',exact:true}).click();
    await expect(detail).toContainText('已安装');
    await expect(modal.getByRole('button',{name:/安装|下载/})).toHaveCount(0);
    await page.getByRole('button',{name:/设置封面/}).click();
    await page.locator('#workshop-cover-editor input[type=file]').setInputFiles(process.env.WORKSHOP_SMOKE_COVER);
    await expect(modal.getByRole('cell',{name:'cover.png',exact:true})).toBeVisible();
    await page.getByRole('button',{name:'保存封面',exact:true}).click();
    await expect(page.getByRole('textbox',{name:'封面状态',exact:true})).toHaveValue(/封面已保存/,{timeout:20000});
    await page.screenshot({path:path.join(evidence,'desktop-cover-install.png'),fullPage:true});
    await close.click();
    await expect(modal).toBeHidden();
    await cards.last().hover();
    await cards.last().getByRole('button',{name:'查看详情',exact:true}).click();
    await expect(page.locator('#workshop-cover-editor')).toBeHidden();
    await expect(page.locator('#workshop-withdraw-editor')).toBeHidden();
    await expect(modal).toContainText('测试音色 01');
    await page.locator('#workshop-modal').click({position:{x:5,y:5}});
    await expect(modal).toBeHidden();
    await page.reload();
    await page.locator('#sidebar > button').click();
    await expect(cards).toHaveCount(9,{timeout:20000});
    await cards.first().getByRole('button',{name:'查看详情',exact:true}).focus();
    await page.keyboard.press('Enter');
    await expect(detail).toContainText('已安装');
    await expect(close).toBeFocused();
    await page.keyboard.press('Shift+Tab');
    await expect(modal).toBeVisible();
    if (!await page.locator('#workshop-modal').evaluate(e=>e.contains(document.activeElement))) throw Error('Focus escaped dialog');
    await page.keyboard.press('Escape');
    await expect(modal).toBeHidden();
    const search = page.getByRole('textbox',{name:'搜索名称或作者',exact:true});
    await search.fill('不存在');
    await search.press('Enter');
    await expect(cards).toHaveCount(0);
    await expect(page.locator('.workshop-grid-empty')).toBeVisible();
    await search.fill('');
    await search.press('Enter');
    await expect(cards).toHaveCount(9);
    await page.getByText('上传本地音色',{exact:true}).click();
    const uploader = page.locator('#workshop-uploader');
    await uploader.getByRole('listbox',{name:'本地可用音色',exact:true}).click();
    await page.getByRole('option').first().click();
    await uploader.getByRole('textbox',{name:'作者',exact:true}).fill('浏览器作者');
    await uploader.getByRole('textbox',{name:'简介',exact:true}).fill('隔离临时音色的上传表单验证');
    const upload = uploader.getByRole('button',{name:'上传选中音色',exact:true});
    const uploadStatus = uploader.getByRole('textbox',{name:'上传状态',exact:true});
    await upload.click();
    await expect(uploadStatus).toHaveValue(/RIGHTS_REQUIRED/);
    await expect(upload).toBeEnabled();
    await uploader.getByRole('checkbox').check();
    await upload.click();
    await expect(uploadStatus).toHaveValue(/正在校验/);
    await expect(upload).toBeDisabled();
    await expect(uploadStatus).toHaveValue(/上传成功/,{timeout:20000});
    await expect(upload).toBeEnabled();
    await expect(cards).toHaveCount(10,{timeout:20000});
    await page.screenshot({path:path.join(evidence,'upload-feedback.png'),fullPage:true});
    await page.setViewportSize({width:390,height:844});
    await fs.writeFile(path.join(evidence,'mobile-dom.json'), JSON.stringify(await page.locator('.gradio-container, main, #app-shell, #page-content, #workshop-browser').evaluateAll(es=>es.map(e=>({tag:e.tagName,cls:e.className,id:e.id,box:e.getBoundingClientRect().toJSON(),padding:getComputedStyle(e).padding,width:getComputedStyle(e).width}))),null,2));
    await page.screenshot({path:path.join(evidence,'mobile-grid.png'),fullPage:true});
    await cards.first().getByRole('button',{name:'查看详情',exact:true}).focus();
    await page.keyboard.press('Enter');
    await expect(modal).toBeVisible();
    const box=await modal.boundingBox();
    if(box.x<0 || box.x+box.width>392 || box.y<0 || box.y+box.height>846) throw Error('Dialog outside mobile viewport');
    await page.screenshot({path:path.join(evidence,'mobile-dialog.png')});
    await close.click();
    await expect(modal).toBeHidden();
    const width = await page.evaluate(()=>({scroll:document.documentElement.scrollWidth,width:innerWidth}));
    if(width.scroll>width.width+2) throw Error('Mobile horizontal overflow: '+JSON.stringify(width));
    await cards.first().getByRole('button',{name:'查看详情',exact:true}).click();
    await page.getByRole('button',{name:/下架我上传的音色/}).click();
    await page.getByRole('button',{name:'确认下架',exact:true}).click();
    await expect(page.getByRole('textbox',{name:'下架状态',exact:true})).toHaveValue(/请先确认/);
    await page.getByRole('checkbox',{name:'我确认从工坊下架此音色，保留各客户端的本地副本',exact:true}).check();
    await page.getByRole('button',{name:'确认下架',exact:true}).click();
    await expect(modal).toBeHidden();
    await expect(cards).toHaveCount(9);
    await expect(page.getByRole('textbox',{name:'卡片操作结果',exact:true})).toHaveValue(/本地副本保留/);
    await page.reload();
    await page.locator('#sidebar > button').click();
    await expect(cards).toHaveCount(9);
    if(errors.length) throw Error(errors.join('\n'));
    await fs.writeFile(path.join(evidence,'result.json'),JSON.stringify({passed:true,errors,top,scenarios:['real HTTP list/download/cover','install with sanitizer test double','confirmation guard','empty search','keyboard selection','upload form validation/progress/success/automatic refresh','card install/uninstall/restore and no duplicate install controls','modal details, owner-only cover editor, Escape, backdrop, focus trap','owner withdrawal, confirmation guard, non-owner hidden, reload persistence','390px layout']},null,2));
    console.log('Workshop browser smoke: PASS (sanitizer test double; no GPU synthesis)');
  } catch(e) {
    await fs.writeFile(path.join(evidence,'modal-failure.json'),JSON.stringify(await page.evaluate(()=>({modal:document.querySelector('#workshop-modal')?.outerHTML,focused:document.activeElement?.tagName,body:document.body.getAttribute('style')})),null,2));
    await page.screenshot({path:path.join(evidence,'failure.png'),fullPage:true});
    throw e;
  } finally {await browser.close();}
}
main().catch(e=>{console.error(e);process.exitCode=1;});
